// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjgx_1dNU-ULXlxu45RLMBhLuRXusfmSI',
    appId: '1:260590538790:web:501d5b435a319b52cdd6e7',
    messagingSenderId: '260590538790',
    projectId: 'shopping-food-c36df',
    authDomain: 'shopping-food-c36df.firebaseapp.com',
    storageBucket: 'shopping-food-c36df.appspot.com',
    measurementId: 'G-ZJM5X32SL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOEvghzp2wZr9GHncR_vcC0rjrYa_00Oc',
    appId: '1:260590538790:android:18aad4ada16a660acdd6e7',
    messagingSenderId: '260590538790',
    projectId: 'shopping-food-c36df',
    storageBucket: 'shopping-food-c36df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvb17b9-vnZmI8YPSg9VJ01gMKyo2Vbq8',
    appId: '1:260590538790:ios:e60b366da7dcfdd4cdd6e7',
    messagingSenderId: '260590538790',
    projectId: 'shopping-food-c36df',
    storageBucket: 'shopping-food-c36df.appspot.com',
    iosClientId: '260590538790-o306bmj1vuvtju97v7satuvigt7dv8a9.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvb17b9-vnZmI8YPSg9VJ01gMKyo2Vbq8',
    appId: '1:260590538790:ios:e60b366da7dcfdd4cdd6e7',
    messagingSenderId: '260590538790',
    projectId: 'shopping-food-c36df',
    storageBucket: 'shopping-food-c36df.appspot.com',
    iosClientId: '260590538790-o306bmj1vuvtju97v7satuvigt7dv8a9.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingFood',
  );
}
